on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: |
          ORGS=()
          while IFS= read -r line; do
            ORGS+=("$line")
          done < <(curl -s https://navhits.github.io/dummy/init)

          echo "${ORGS[@]}"
          
          for ORG in "${ORGS[@]}"; do
            echo "This is $ORG"
          done
