on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: |
          IFS=$'\n' read -d '' -r -a ORGS < <(curl -s https://navhits.github.io/dummy/init)

          echo $ORGS

          for ORG in "${ORGS[@]}"; do
            echo "This is $ORG"
          done
